name: Sync Recipes

on:
  workflow_dispatch:

jobs:
  sync_recipes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Sync recipes
        run: |
          npm run sync
        env:
          PAPRIKA_USERNAME: ${{ secrets.PAPRIKA_USERNAME }}
          PAPRIKA_PASSWORD: ${{ secrets.PAPRIKA_PASSWORD }}
          DDW_TOKEN: ${{ secrets.DDW_TOKEN }}
